### PR TITLE
Symfony 3, PSR-2, PSR-4

### LINKED ISSUE #77: Support Symfony 3.0
Hi,

some ideas to use this bundle with the new version of Symfony ( 3.0 ) please ?

Can we have an update of this bundle ?

Thanks

### PR DESCRIPTION
**Pull request by boekkooi**
Hi there,

First of all I'm sorry for this massive PR.

This PR adds support for Symfony 3 (59f4791) and changes the code base to use PSR-4 (c58de76) and PSR-2 (14c9bcd, f0cb533). 
It also adds some tweaks:
- Added gitattributes and editorconfig (8f7cbbe) 
- Enabled testing of lowest dependencies and PHP 7 on Travis (0ae761b, 075eb82)
- Cleans up PHPUnit.xml.dist (73dde1d)
- Uses EnumNode instead of ScalarNode for bundle configuration (3450a1e)

Again I'm sorry for the massive PR but I hope you like it.

Cheers,
Warnar

P.S. This PR would make #74, #73, #67, #59 obsolete and fixes #77, #66

### CODE REVIEW

**Comment by HeahDude** [comment]
Looks good! Thanks for that :+1:

**Comment by boekkooi** [comment]
@francisbesset @jfsimon Ping :smile:

**Comment by boekkooi** [comment]
@francisbesset Are you looking for a maintainer for this project? If so I'm willing.

**Comment by nikophil** [comment]
+1  :)

**Comment by thomas2411** [comment]
Saved me, +1 for this Gentleman as a maintainer

**Comment by boekkooi** [comment]
@francisbesset @jfsimon Sorry for nagging but any change for a review and/or merge of this PR? Thanks in advance!

**Comment by francisbesset** [comment]
Really good work!
Thank you.

**Comment by boekkooi** [comment]
No problem thanks for merging :smile: and if you need a extra maintainer for this bundle just give me a buzz

**Comment by francisbesset** [comment]
Done ;)

**Comment by boekkooi** [comment]
@francisbesset Great I will start closing some old issues and PR's

**Comment by HeahDude** [comment]
@boekkooi Thanks for your work! This freshness is very welcome 🎉

**Pull request merged**
